version: 2
jobs:
  build:
    docker:
      - image: golang:1.8
    working_directory: /tmp/kt
    steps:
      - run: 
          name: create artifacts
          command: |
            mkdir artifacts
            echo test > "artifacts/aaa.txt"
            echo test > "artifacts/b b.txt"
            echo test > "artifacts/c?c.txt"
            echo test > "artifacts/d^d.txt"
            echo test > "artifacts/e:e.txt"
            echo test > "artifacts/f+f.txt"
            echo test > "artifacts/g\#.txt"

      - store_artifacts: 
          path: ./artifacts
          destination: tests