version: 2
jobs:
  build:
    docker:
      - image: golang:1.8
    working_directory: /tmp/kt
    steps:
      - run: 
          name: create artifacts
          command: |
            mkdir artifacts
            echo aaa > "artifacts/aaa.txt"
            echo aas > "artifacts/a a.txt"
            echo aad > "artifacts/aa$a.txt"
            echo aaa > "artifacts/aa^a.txt"
            echo aaa > "artifacts/a:aa.txt"
            echo aaa > "artifacts/a+aa.txt"
            echo aaa > "artifacts/a?aa.txt"
            echo aaa > "artifacts/aa\#a.txt"

      - store_artifacts: 
          path: ./artifacts
          destination: tests

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build